modules: viss: ldc: added live tuning support
TexasInstruments/edgeai-tiovx-modules pull request #87
Opened 2022-12-06 20:43 UTC by Brandon-Maciel-TI

2022-12-07 06:49 UTC, ravi-rahul requested changes

2022-12-07 06:49 UTC, ravi-rahul commented on src/tiovx_ldc_module.c
> +
Hi @Brandon-Maciel-TI 

Can we protect it with a macro
and enable it only when needed
via an option in Cmake

2022-12-07 06:49 UTC, ravi-rahul commented on src/tiovx_ldc_module.c
> +
you can take below as reference
https://git.ti.com/cgit/edgeai/edgeai-dl-inferer/tree/cmake/common.cmake?h=develop#n6
https://git.ti.com/cgit/edgeai/edgeai-dl-inferer/tree/cmake/common.cmake?h=develop#n50
https://git.ti.com/cgit/edgeai/edgeai-dl-inferer/tree/dl_inferer/src/ti_dl_inferer.cpp?h=develop#n742

2022-12-07 22:39 UTC, Brandon-Maciel-TI commented on src/tiovx_ldc_module.c
> +
done!

2022-12-08 08:05 UTC, ravi-rahul commented
Hi @Brandon-Maciel-TI 

This is ready to be merged
Please squash all the commits into a single commit

2022-12-15 10:13 UTC, ravi-rahul commented
Hi @Brandon-Maciel-TI 

Please add the appropriate commit message
Please refer to previous commits

2022-12-16 11:41 UTC, ravi-rahul approved these changes

2022-12-16 11:41 UTC, merged